import tick from "./Assets/checkmark.png";
import basic from "./Assets/periodic/basic service.jpg";
import std from "./Assets/periodic/standard service.jpg";
import comper from "./Assets/periodic/comperhensive service.jpg";
import frontbrake from "./Assets/periodic/brake maintaince.jpg";
import rearbrake from "./Assets/periodic/rear brake service.png";
import discser from "./Assets/periodic/disc service.png";
import discturn from "./Assets/periodic/disc turning.jpg";
import ac1 from './Assets/ac/regular.jpg'
import ac2 from './Assets/ac/high performance.jpg'
import ac3 from './Assets/ac/cooling coil.jpg'
import ac4 from './Assets/ac/condensor.jpg'
import ac5 from './Assets/ac/compressor.jpg'
import ac6 from './Assets/ac/radiator.jpg'
import ac7 from './Assets/ac/vbelt.jpg'
import battery1 from './Assets/battery/exide (1).png'
import battery2 from './Assets/battery/amaron.png'
import wheel1 from './Assets/tyre/wheel balance.jpg'
import wheel2 from './Assets/tyre/wheel align.jpg'
import wheel3 from './Assets/tyre/wheel bearing.jpg'
import wheel4 from './Assets/tyre/wheel mud flaps.png'
import paint1 from './Assets/Paint/bumper paint.jpg'
import paint2 from './Assets/Paint/rear bumper.jpg'
import paint3 from './Assets/Paint/Boot Paint.jpg'
import paint4 from './Assets/Paint/whole body.jpg'
import detail1 from './Assets/detail/1image.jpg'
import detail2 from './Assets/detail/2image.jpg'
import detail3 from './Assets/detail/3image.jpg'
import detail4 from './Assets/detail/4 image.jpg'
import wind1 from './Assets/Wind/1.jpg'
import wind2 from './Assets/Wind/2.jpg'
import wind3 from './Assets/Wind/3.jpg'
import wind4 from './Assets/Wind/4.jpg'


export const periodicservice = [
  {
    id: 1,
    cat:"Periodic",
    image: basic,
    price: "Rs 25999",
    amount: 18299,
    title: "Basic Services",
    time: "4 hrs Taken",
    tickmark: tick,
    detailone: "Wiper Fluid Replacement",
    detailtwo: "Battery Water Top Up",
    detailthree: "Engine Oil Replacement",
    detailfour: "Air filter cleaning",
    detailfive: "Wiper Fluid Replacement",
    detailsix: "Oil Filter Replacements",
  },
  {
    id: 2,
    cat:"Periodic",
    image: std,
    price: "Rs.27,999",
    amount: 20299,
    title: "Standard Services",
    time: "8 hrs Taken",
    tickmark: tick,
    detailone: "Frond Brake Pads Service",
    detailtwo: "Fuel filter Change",
    detailthree: "Ac Filter Cleaning",
    detailfour: "Air filter cleaning",
    detailfive: "Coolent Top Up",
    detailsix: "Brake Fluid Top up",
  },
  {
    id: 3,
    cat:"Periodic",
    image: comper,
    price: "Rs.34,999",
    amount: 25599,
    title: "Comperhensive Serivces",
    time: "8 hrs Taken",
    tickmark: tick,
    detailone: "Fuel Filter Checking",
    detailtwo: "Car Scanning",
    detailthree: "Wheel Alignment",
    detailfour: "Engine Oil Replacement",
    detailfive: "Engine Flushing",
    detailsix: "Tyre Rotation",
  },
  {
    id: 4,
    cat:"Periodic",
    image: frontbrake,
    price: "Rs.16,920",
    amount: 13530,
    title: "Brake Maintenance",
    time: "3 hrs Taken",
    tickmark: tick,
    detailone: "One Month Warranty",
    detailtwo: "Opening & fitting pads",
    detailthree: "Applicable two sets",
    detailfour: "Front Brake Cleaning",
    detailfive: "Front brakes replacement",
    detailsix: "Incpection of Brake Pads ",
  },
  {
    id: 5,
    cat:"Periodic",
    image: rearbrake,
    price: "Rs.15,675",
    amount: 12540,
    title: "Rear Brake Servicesv",
    time: "3 hrs Taken",
    tickmark: tick,
    detailone: "One Month Warranty",
    detailtwo: "Opening & fitting pads",
    detailthree: "Applicable two sets",
    detailfour: "Front brakes replacement",
    detailfive: "Incpection of Brake Pads",
    detailsix: "Front Brake Cleaning",
  },
  {
    id: 6,
    cat:"Periodic",
    image: discser,
    price: "Rs.16,250",
    amount: 13299,
    title: "Front Disc Brakes Services",
    time: "5 hrs Taken",
    tickmark: tick,
    detailone: "Front Disc Brake Replacement",
    detailtwo: "Increases Brake Life & Safety",
    detailthree: "Open & fitting of Disc Brakes",
    detailfour: "Reduces Vibration & Noises",
    detailfive: "Free Pickup & Drop",
    detailsix: "Corrosion Resistance",
  },
  {
    id: 7,
    cat:"Periodic",
    image: discturn,
    price: "Rs.3,999",
    amount: 2299,
    title: "Disc turning",
    time: "4 hrs Taken",
    tickmark: tick,
    detailone: "1 Month Warranty",
    detailtwo: "Opening of Brakes Discs",
    detailthree: "Fitting of Brakes Discs",
    detailfour: "Applicable for 2 sets Discs",
    detailfive: "Incpection of Brake Discs",
    detailsix: "Resurfacing of Brake Discs",
  },

  {
    id: 8,
    cat:"ac",
    image: ac1,
    price: "Rs.3,999",
    amount: 2999,
    title: "Regular Ac Services",
    time: "4 hrs Taken",
    tickmark: tick,
    detailone: "One Month warranty",
    detailtwo: "Ac Vent Cleaning",
    detailthree: "Ac Gas (upto 400 gms)",
    detailfour: "Air filter cleaning",
    detailfive: "Ac Inspection",
    detailsix: "Condnser Cleaning",
  },
  {
    id: 9,
    cat:"ac",
    image: ac2,
    price: "Rs.12,850",
    amount: 8999,
    title: "High Performance Ac Service",
    time: "8 hrs Taken",
    tickmark: tick,
    detailone: "Ac Vent Cleaning",
    detailtwo: "Ac Gas (upto 600 gms)",
    detailthree: "Cooling Coil Cleaning",
    detailfour: "Ac Leak Test",
    detailfive: "Dashboard Cleaning",
    detailsix: "Compressor oil cleaning",
  },
  {
    id: 10,
    cat:"ac",
    image: ac3,
    price: "Rs.41,284",
    amount: 28999,
    title: "Cooling Coil Services",
    time: "8 hrs Taken",
    tickmark: tick,
    detailone: "3 Month Warranty",
    detailtwo: "Cooling Coil Services",
    detailthree: "Ac Pipe, Valve Sensors Cost",
    detailfour: "Free Pickup & Drop",
    detailfive: "Spare parts Cost Only",
    detailsix: "Gas, Compressor oil Cost",
  },
  {
    id: 11,
    cat:"ac",
    image: ac4,
    price: "Rs.25,700",
    amount: 17799,
    title: "Condensor Services",
    time: "8 hrs Taken",
    tickmark: tick,
    detailone: "Condensor Replacements",
    detailtwo: "Spare Parts Cost Only",
    detailthree: "Free Pickup & Drop",
    detailfour: "Ac and Gas cost",
    detailfive: "Coolant and Radiator",
    detailsix: "3 Month Warranty",
  },
  {
    id: 12,
    cat:"ac",
    image: ac5,
    price: "Rs.71,140",
    amount: 49799,
    title: "Compressor Services",
    time: "8 hrs Taken",
    tickmark: tick,
    detailone: "Compressor Replacement",
    detailtwo: "Spare parts Cost only",
    detailthree: "Free Pickup & Drops",
    detailfour: "Compressor Oil Cost",
    detailfive: "Ac Pipe, Valve cost",
    detailsix: "3 Month Warranty",
  },
  {
    id: 13,
    cat:"ac",
    image: ac6,
    price: "Rs.4,999",
    amount: 3299,
    title: "Radiator Services",
    time: "2 hrs Taken",
    tickmark: tick,
    detailone: "Free Pickup & Drop",
    detailtwo: "Coolant & Draining",
    detailthree: "Anti-Freeze Cooling",
    detailfour: "Coolant Leakage",
    detailfive: "Radiator Flushing",
    detailsix: "Radiator Cleaning",
  },
  {
    id: 14,
    cat:"ac",
    image: ac7,
    price: "Rs.9,439",
    amount: 8499,
    title: "V-belt Services",
    time: "6 hrs Taken",
    tickmark: tick,
    detailone: "Pulley, Bearing cost",
    detailtwo: "1 Month Warranty",
    detailthree: "Free pickup & Drop",
    detailfour: "Scanning Cost",
    detailfive: "Opening of v belt",
    detailsix: "V-belt Replacement",
  },

  {
    id: 15,
    cat:"battery",
    image: battery1,
    price: "Rs.10,899",
    amount: 9799,
    title: "Exide Battery",
    time: "80 Amp Hour",
    tickmark: tick,
    detailone: "55 Month warranty",
    detailtwo: "Free Cost Installtion",
    detailthree: "Free Pickup & Drop",
    detailfour: "Old Battery Price Included",
    detailfive: "Available at Doorstep",
    detailsix: "Free Installtion",
  },
  {
    id: 16,
    cat:"battery",
    image: battery2,
    price: "Rs.12,850",
    amount: 8999,
    title: "Amaron Battery",
    time: "80 Amp Hour",
    tickmark: tick,
    detailone: "55 Month warranty",
    detailtwo: "Free Cost Installtion",
    detailthree: "Free pickup & Drop",
    detailfour: "Old Battery Price Included",
    detailfive: "Available at Doorstep",
    detailsix: "Free Installtion",
  },

  {
    id: 17,
    cat:"tyre",
    image: wheel1,
    price: "Rs.22,899",
    amount: 15799,
    title: "Wheel Balancing",
    time: "8 hour Taken",
    tickmark: tick,
    detailone: "Automated Wheel Balance",
    detailtwo: "Alloy Weights",
    detailthree: "Steering Adjustments",
    detailfour: "Weight Correction",
    detailfive: "Laser Assisted Alignment",
    detailsix: "Camber Adjustment",
  },
  {
    id: 18,
    cat:"tyre",
    image: wheel2,
    price: "Rs.16,850",
    amount: 11999,
    title: "Wheel Alignments",
    time: "5 hour Taken",
    tickmark: tick,
    detailone: "Automated Wheel Balance",
    detailtwo: "Alloy Weights",
    detailthree: "Steering Adjustments",
    detailfour: "Weight Correction",
    detailfive: "Laser Assisted Alignment",
    detailsix: "Camber Adjustment",
  },
  {
    id: 19,
    cat:"tyre",
    image: wheel3,
    price: "Rs.22,850",
    amount: 16999,
    title: "Wheel Bearing Service",
    time: "3 hour Taken",
    tickmark: tick,
    detailone: "Automated Wheel Balance",
    detailtwo: "Alloy Weights",
    detailthree: "Steering Adjustments",
    detailfour: "Weight Correction",
    detailfive: "Laser Assisted Alignment",
    detailsix: "Camber Adjustment",
  },
  {
    id: 20,
    cat:"tyre",
    image: wheel4,
    price: "Rs.5,850",
    amount: 3999,
    title: "Wheel Mud Flap",
    time: "8 hour Taken",
    tickmark: tick,
    detailone: "Automated Wheel Balance",
    detailtwo: "Alloy Weights",
    detailthree: "Steering Adjustments",
    detailfour: "Weight Correction",
    detailfive: "Laser Assisted Alignment",
    detailsix: "Camber Adjustment",
  },

  {
    id: 21,
    cat:"paint",
    image: paint1,
    price: "Rs.4,689",
    amount: 3999,
    title: "Bumper Painting",
    time: "24 hour Taken",
    tickmark: tick,
    detailone: "2 Year Warranty on Paint",
    detailtwo: "Grade a Primer Applied",
    detailthree: "Remove Minor Dent & Scartch",
    detailfour: "High Quality Dupont Paint",
    detailfive: "Panel Rubbing & Polishing",
    detailsix: "Clear Coat Protective paint",
  },
  {
    id: 22,
    cat:"paint",
    image: paint2,
    price: "Rs.4,850",
    amount: 3999,
    title: "Rear Bumper Painting",
    time: "24 hour Taken",
    tickmark: tick,
    detailone: "2 Year Warranty on Paint",
    detailtwo: "Grade a Primer Applied",
    detailthree: "Remove Minor Dent & Scartch",
    detailfour: "High Quality Dupont Paint",
    detailfive: "Panel Rubbing & Polishing",
    detailsix: "Clear Coat Protective paint",
  },
  {
    id: 23,
    cat:"paint",
    image: paint3,
    price: "Rs.3,850",
    amount: 2999,
    title: "Boot Painting",
    time: "24 hour Taken",
    tickmark: tick,
    detailone: "2 Year Warranty on Paint",
    detailtwo: "Grade a Primer Applied",
    detailthree: "Remove Minor Dent & Scartch",
    detailfour: "High Quality Dupont Paint",
    detailfive: "Panel Rubbing & Polishing",
    detailsix: "Clear Coat Protective paint",
  },
  {
    id: 24,
    cat:"paint",
    image: paint4,
    price: "Rs.22,850",
    amount: 19999,
    title: "Whole Body Painting",
    time: "8 days Taken",
    tickmark: tick,
    detailone: "2 Year Warranty on Paint",
    detailtwo: "Grade a Primer Applied",
    detailthree: "Remove Minor Dent & Scartch",
    detailfour: "High Quality Dupont Paint",
    detailfive: "Panel Rubbing & Polishing",
    detailsix: "Clear Coat Protective paint",
  },

  {
    id: 25,
    cat:"detail",
    image: detail1,
    price: "Rs.8,659",
    amount: 5999,
    title: "Car Rubbing & Polishing",
    time: "6 hour Taken",
    tickmark: tick,
    detailone: "Pressure Car Washing",
    detailtwo: "Alloy Polishing",
    detailthree: "Rubbing with 3M Compound",
    detailfour: "Tyre Dressing",
    detailfive: "Machine Rubbing",
    detailsix: "3M Wax Polishing",
  },
  {
    id: 26,
    cat:"detail",
    image: detail2,
    price: "Rs.34,850",
    amount: 31999,
    title: "Meguiar's Ceramic Coating",
    time: "Take 3 Days",
    tickmark: tick,
    detailone: "Complete Paint Corrections",
    detailtwo: "Remove Minor Scratchs",
    detailthree: "Exterior Car Wash",
    detailfour: "2 Layer of Coating",
    detailfive: "Deep All Round Spa",
    detailsix: "Ultra Shine Protection",
  },
  {
    id: 27,
    cat:"detail",
    image: detail3,
    price: "Rs.97,850",
    amount: 85999,
    title: "Paint Protection Films",
    time: "Takes 6 Days",
    tickmark: tick,
    detailone: "3 Year Warranty",
    detailtwo: "Every 3 Years",
    detailthree: "Every PPF",
    detailfour: "Remove Minor Scartchs",
    detailfive: "External Car Wash",
    detailsix: "Ultra Shine Polishing",
  },
  {
    id: 28,
    cat:"detail",
    image: detail4,
    price: "Rs.9,950",
    amount: 7999,
    title: "Silencer Coating",
    time: "Take 6 Hours",
    tickmark: tick,
    detailone: "3 Month Warranty",
    detailtwo: "Recommended Every 1 Year",
    detailthree: "Silencer Anti-rusting Coating",
    detailfour: "2 Layer of Protection",
    detailfive: "Silencer Corrosion Protection",
    detailsix: "Underbody Teflon Coating",
  },


  {
    id: 29,
    cat:"wind",
    image: wind1,
    price: "Rs.61,789",
    amount: 55999,
    title: "Frond Windsheild Services",
    time: "Take 6 Hours",
    tickmark: tick,
    detailone: "1 Month Warranty",
    detailtwo: "WindSheild (ISI Approved)",
    detailthree: "Sensor Charges Additional",
    detailfour: "Free Pickup & Drop",
    detailfive: "Opening & Fitting WindSheild",
    detailsix: "Consumables",
  },
  {
    id: 30,
    cat:"wind",
    image: wind2,
    price: "Rs.54,850",
    amount: 48999,
    title: "Rear WindSheild Services",
    time: "Take 6 Hours",
    tickmark: tick,
    detailone: "1 Month Warranty",
    detailtwo: "WindSheild (ISI Approved)",
    detailthree: "Free Pickup & Drop",
    detailfour: "Defogger Charges Additional",
    detailfive: "Opening & Fitting WindSheild",
    detailsix: "Consumable",
  },{
    id: 31,
    cat:"wind",
    image: wind3,
    price: "Rs.97,850",
    amount: 89999,
    title: "Front HeadLights Services",
    time: "Take 4 Hours",
    tickmark: tick,
    detailone: "1 Month Warranty",
    detailtwo: "Recommonded for crack/damages",
    detailthree: "Headlight OES",
    detailfour: "Free Pickup & Drop",
    detailfive: "Opening & Fitting of Headlights",
    detailsix: "LED s Additional",
  },{
    id: 32,
    cat:"wind",
    image: wind4,
    price: "Rs.29,950",
    amount: 7999,
    title: "Silencer Coating",
    time: "Take 6 Hours",
    tickmark: tick,
    detailone: "3 Month Warranty",
    detailtwo: "Recommended Every 1 Year",
    detailthree: "Silencer Anti-rusting Coating",
    detailfour: "2 Layer of Protection",
    detailfive: "Silencer Corrosion Protection",
    detailsix: "Underbody Teflon Coating",
  },

];
